### ISSUE TITLE
Fix newest spt aki 3.2.1

### ISSUE THREAD

**Issue by Dominikodz** [KittehKun/welcome-messages#2]
What's the point to LogWithColor when you make it white, right?

Lane 18, src/messages.js
`
logger.info("Loading: Custom Welcome Messages");
`

logger.info has white color sooo... Also once i cant do pull request, I create an issue :)

Edit: I just saw that js is using "LogTextColor_1", but You didn't use it 🙄

**Comment by KittehKun** [comment]
Line has been cleaned up and the release has been updated.

-KittehKun
